# Hyperparameters
seed : 1111
do_shuffle : False
n_data_max : null
cross_val_folds : 5
do_test_pred : True

# Logging
do_wandb : False
wandb_config:
  project : wandb_project_example
  entity : wandb_entity_example
do_tb : True
do_cli : False
do_tqdm : True

# ---------- Team features ----------
teamfeatures_config :

  # Metric and features to drop
  metrics_to_drop :
    - HOME_TEAM_SHOTS_TOTAL
  features_to_drop:
    - AWAY_TEAM_YELLOWCARDS_5_last_match_std
    - misspled_feature_example

  # Non-null indicator features
  add_non_null_indicator_feature : True
  add_non_null_indicator_metric : True

  # Imputation
  imputation_method : median

  # Other
  n_data_max : null
  verbose : 1

# ---------- Player features ----------
playerfeatures_config :
  # Metric and features to drop
  metrics_to_drop :
    # We have to drop cause its 100% null
    - PLAYER_LONG_BALLS
    - PLAYER_LONG_BALLS_WON
    - PLAYER_SHOTS_OFF_TARGET
    # Potentially drop cause its 70 and 35% null
    - PLAYER_PUNCHES
    - PLAYER_ACCURATE_PASSES_PERCENTAGE
  features_to_drop : []

  # Non-null indicator features
  add_non_null_indicator_feature : True
  add_non_null_indicator_metric : True

  # Imputation
  imputation_method : median

  # Other
  n_data_max : null
  verbose : 1


# ---------- Aggregator ----------
aggregator_config :
  role_grouping:
    - ALL
    # - ATK
  operations:
    - mean
    # - min

# Defaults sub-configs and other Hydra config.
defaults:
  - _self_
  - trainer : xgb
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled 


# Hydra config, do not change.
hydra:
  output_subdir: null
  run:
    dir: .