# Hyperparameters
seed : 1111
do_shuffle : False
n_data_max : 99999999999
cross_val_folds : 5
do_test_pred : True

# Logging
do_wandb : False
wandb_config:
  project : wandb_project_example
  entity : wandb_entity_example
do_tb : True
do_cli : False
do_tqdm : True

# ---------- Features loader ----------
loaders:
  # The labels loader
  labels :
    load : True
    use : True

  # The team features loader
  teamfeatures :
    load : True
    use : True
    metrics_to_drop : []
    features_to_drop: []
    # A method for dealing with missing values. Among 'mean', 'median', 'mode'
    imputation_method : mean
    # Whether to create a new indicator feature for each feature with missing values, or for each metric if all aggregated features have missing values
    add_non_null_indicator_feature : False
    add_non_null_indicator_metric : False
    verbose : 1
    
  # playerfeatures :
  #   load : True
  #   use : False
  #   metrics_to_drop :
  #     # We have to drop cause its 100% null
  #     - HOME_PLAYER_LONG_BALLS
    #   - HOME_PLAYER_LONG_BALLS_WON
    #   - HOME_PLAYER_SHOTS_OFF_TARGET
    #   # Potentially drop cause its 70 and 35% null
    #   - PLAYER_PUNCHES
    #   - PLAYER_ACCURATE_PASSES_PERCENTAGE

# Features creator
creators: {}

# Defaults sub-configs and other Hydra config.
defaults:
  - _self_
  - trainer : xgb
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled 


# Hydra config, do not change.
hydra:
  output_subdir: null
  run:
    dir: .