# Hyperparameters
seed : 1111
do_shuffle : False
n_data_max : 99999999999
cross_val_folds : 5

# Logging
do_wandb : False
wandb_config:
  project : wandb_project_example
  entity : wandb_entity_example
do_tb : True
do_cli : False
do_tqdm : True

# Features loader
loaders:
  labels :
    load : True
    use : True
  teamfeatures :
    load : True
    use : True
  # playerfeatures :
  #   load : True
  #   use : False

# Features creator
creators: {}

# Defaults sub-configs and other Hydra config.
defaults:
  - _self_
  - trainer : xgb
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled 


# Hydra config, do not change.
hydra:
  output_subdir: null
  run:
    dir: .