SPECIFIC_TEAMFEATURES = [
    "HOME_ID",
    "HOME_TEAM_NAME",
    "HOME_LEAGUE",
    "AWAY_ID",
    "AWAY_TEAM_NAME",
    "AWAY_LEAGUE",
]
SPECIFIC_PLAYERFEATURES = [
    "ID",
    "LEAGUE",
    "TEAM_NAME",
    "POSITION",
    "PLAYER_NAME",
]


# Player features manually crafted
OFFENSIVE_POSITIVE_PLAYERFEATURES = [
    "PLAYER_AERIALS_WON",
    "PLAYER_DRIBBLES_ATTEMPTS",
    "PLAYER_ASSISTS",
    "PLAYER_GOALS",
    "PLAYER_PENALTIES_WON",
    "PLAYER_SHOTS_TOTAL",
    "PLAYER_TOTAL_CROSSES",
    "PLAYER_LONG_BALLS",
]

OFFENSIVE_NEGATIVE_PLAYERFEATURES = [
    "PLAYER_OFFSIDES",
]

DEFENSIVE_POSITIVE_PLAYERFEATURES = [
    "PLAYER_BLOCKED_SHOTS",
    "PLAYER_CLEARANCES",
    "PLAYER_CLEARANCES_OFFLINE",
    "PLAYER_SHOTS_BLOCKED",
    "PLAYER_TACKLES",
]
DEFENSIVE_NEGATIVE_PLAYERFEATURES = [
    "PLAYER_GOALS_CONCEDED",
    "PLAYER_INTERCEPTIONS",
    "PLAYER_OWN_GOALS",
    "PLAYER_PENALTIES_COMMITTED",
]

SHOOTING_POSITIVE_PLAYERFEATURES = [
    "PLAYER_ACCURATE_CROSSES",
    "PLAYER_ACCURATE_PASSES",
    "PLAYER_HIT_WOODWORK",
    "PLAYER_PASSES",
    "PLAYER_PENALTIES_SCORED",
    "PLAYER_SHOTS_ON_TARGET",
    "PLAYER_LONG_BALLS_WON",
    "PLAYER_ACCURATE_PASSES_PERCENTAGE",
]
SHOOTING_NEGATIVE_PLAYERFEATURES = [
    "PLAYER_PENALTIES_MISSES",
    "PLAYER_SHOTS_OFF_TARGET",
]

FOOTWORK_POSITIVE_PLAYERFEATURES = [
    "PLAYER_DUELS_WON",
    "PLAYER_SUCCESSFUL_DRIBBLES",
    "PLAYER_TOTAL_DUELS",
]
FOOTWORK_NEGATIVE_PLAYERFEATURES = [
    "PLAYER_DISPOSSESSED",
    "PLAYER_DRIBBLES_PAST",
    "PLAYER_DUELS_LOST",
]

TIREDNESS_PLAYERFEATURES = [
    "PLAYER_MINUTES_PLAYED",
    "PLAYER_STARTING_LINEUP",
]

GOALKEEPER_PLAYERFEATURES = [
    "PLAYER_GOALKEEPER_GOALS_CONCEDED",
    "PLAYER_PENALTIES_SAVED",
    "PLAYER_SAVES",
    "PLAYER_SAVES_INSIDE_BOX",
]

BEHAVIOR_POSITIVE_PLAYERFEATURES = [
    "PLAYER_BIG_CHANCES_CREATED",
    "PLAYER_CAPTAIN",
    "PLAYER_KEY_PASSES",
]
BEHAVIOR_NEGATIVE_PLAYERFEATURES = [
    "PLAYER_ERRORS_LEAD_TO_GOAL",
    "PLAYER_FOULS",
    "PLAYER_FOULS_DRAWN",
    "PLAYER_CHANCES_MISSED",
    'PLAYER_REDCARDS',
    "PLAYER_YELLOWCARDS",
    "PLAYER_PUNCHES",
]

MISC_PLAYERFEATURES = [
    "PLAYER_RATING",
]

